load exp2I_Vds10mV
load exp2I_Vds10mV,
load exp2Vg_Vds10mV
load exp2Vg_VdsVdd
load exp2ParallelI_Vds10mV
load exp2ParallelI_VdsVdd
load exp2ParallelVg_Vds10mV
load exp2ParallelVg_VdsVdd
load exp2SeriesI_Vds10mV
load exp2SeriesI_VdsVdd,
load exp2SeriesVg_Vds10mV
load exp2SeriesVg_VdsVdd
load exp3Iina
load exp3Iinb
load exp3Iouta
load exp3Vda
load exp3Vdb
load exp3Vsa
load exp3Vsb
load exp3Vsb2